version: "3"
services:
  server:
    container_name: app-container
    image: app-image
    build: .
    restart: always
    ports:
      - 80:8080
    depends_on: 
      - mydb

  mydb:
    container_name: mysql-container
    platform: linux/arm64/v8
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: demouser
      MYSQL_PASSWORD: demopass
      MYSQL_ROOT_PASSWORD: demopass



  # use env_file: .env
  # mydb:
  #   container_name: mydb
  #   platform: linux/arm64/v8
  #   image: mysql:latest
  #   restart: always
  #   ports:
  #     - 3313:3306
  #   env_file:
  #     - .env






